# --- path ---
POSTERIOR_LIST="file_list.txt" 
CHROM_FILE="chrom.txt"
SCRIPT_DIR="./scripts"

# --- para ---
THRESHOLD_P1=0.9
ITERATIONS=100
THREADS=8

# --- slurm ---
PARTITION="long"
CPUS=8
MEM="40G"

# --- output ---
FINAL_PROB_BED="all_chromosomes_final_prob.bed"
THRESHOLD_RESULT="global_threshold_97.5.txt"
PLOT_PREFIX="Manhattan_Cumulative_Prob"
